baseurl = "/"
languageCode = "en-us"
title = "Test Branch"

[params]
  description = "Hive Your Mind."

[[menu.main]]
    name = "Page"
    url  = "/page"
    weight = 1
[[menu.main]]
    name = "Groups"
    url  = "/groupss"
    weight = 2
[[menu.main]]
    name = "Invite"
    url  = "/invite"
    weight = 3
[[menu.main]]
    name = "Directory of groups"
    url  = "/directory"
    weight = 4
[[menu.main]]
    name = "Join a Hivemind"
    url  = "/join"
    weight = 5
